name: anno1800_fanapp
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  
  cached_network_image: ^0.8.0
  flutter_screenutil: ^0.5.2
  webfeed: ^0.4.2
  flutter_html: ^0.9.6
  url_launcher: ^5.0.2
  http: ^0.12.0+2
  uuid: ^2.0.1
  intl: ^0.15.8
  timeago: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/background.png
   - assets/logo.png
   - assets/icons/
